/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.dark.format;

import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import models.PresensiModel;

/**
 *
 * @author iel
 */
public class presensiTemplate extends javax.swing.JPanel implements ListCellRenderer<PresensiModel> {

    /**
     * Creates new form NewJPanel
     */
    public presensiTemplate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAbsen = new javax.swing.JPanel();
        label_nama = new javax.swing.JLabel();
        label_absen = new javax.swing.JLabel();
        label_waktu = new javax.swing.JLabel();
        label_Kehadiran = new javax.swing.JLabel();

        panelAbsen.setBackground(new java.awt.Color(32, 34, 37));

        label_nama.setFont(new java.awt.Font("Poppins", 1, 25)); // NOI18N
        label_nama.setForeground(new java.awt.Color(142, 146, 151));
        label_nama.setText("John Doe");

        label_absen.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        label_absen.setForeground(new java.awt.Color(142, 146, 151));
        label_absen.setText("Absen 12");

        label_waktu.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        label_waktu.setForeground(new java.awt.Color(142, 146, 151));
        label_waktu.setText("06:00:00");

        label_Kehadiran.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        label_Kehadiran.setForeground(new java.awt.Color(96, 221, 65));
        label_Kehadiran.setText("Hadir");

        javax.swing.GroupLayout panelAbsenLayout = new javax.swing.GroupLayout(panelAbsen);
        panelAbsen.setLayout(panelAbsenLayout);
        panelAbsenLayout.setHorizontalGroup(
            panelAbsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAbsenLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelAbsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nama)
                    .addComponent(label_absen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(panelAbsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_waktu)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAbsenLayout.createSequentialGroup()
                        .addComponent(label_Kehadiran)
                        .addGap(20, 20, 20)))
                .addGap(29, 29, 29))
        );
        panelAbsenLayout.setVerticalGroup(
            panelAbsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAbsenLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(panelAbsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama)
                    .addComponent(label_Kehadiran))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(panelAbsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_waktu)
                    .addComponent(label_absen))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelAbsen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_Kehadiran;
    private javax.swing.JLabel label_absen;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_waktu;
    private javax.swing.JPanel panelAbsen;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends PresensiModel> jlist, PresensiModel e, int i, boolean bln, boolean bln1) {
        this.label_Kehadiran.setText(e.getStatus());
        this.label_nama.setText(e.getNama());
        this.label_waktu.setText(e.getWaktu());
        this.label_absen.setText(e.getNomor_absen());
        
        return this;
    }

}
