/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.dark.format;

import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import models.PresensiModel;

/**
 *
 * @author iel
 */
public class presensiTemplate extends javax.swing.JPanel implements ListCellRenderer<PresensiModel> {

    /**
     * Creates new form NewJPanel
     */
    public presensiTemplate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelAbsen = new javax.swing.JPanel();
        label_nama = new javax.swing.JLabel();
        label_absen = new javax.swing.JLabel();
        label_waktu = new javax.swing.JLabel();
        label_Kehadiran = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        panelAbsen.setBackground(new java.awt.Color(32, 34, 37));
        panelAbsen.setMaximumSize(new java.awt.Dimension(0, 32767));
        panelAbsen.setPreferredSize(new java.awt.Dimension(200, 105));

        label_nama.setFont(new java.awt.Font("Poppins", 1, 25)); // NOI18N
        label_nama.setForeground(new java.awt.Color(142, 146, 151));
        label_nama.setText("John Doe");

        label_absen.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        label_absen.setForeground(new java.awt.Color(142, 146, 151));
        label_absen.setText("Absen 12");

        label_waktu.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        label_waktu.setForeground(new java.awt.Color(142, 146, 151));
        label_waktu.setText("06:00");

        label_Kehadiran.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        label_Kehadiran.setForeground(new java.awt.Color(96, 221, 65));
        label_Kehadiran.setText("Hadir");

        javax.swing.GroupLayout panelAbsenLayout = new javax.swing.GroupLayout(panelAbsen);
        panelAbsen.setLayout(panelAbsenLayout);
        panelAbsenLayout.setHorizontalGroup(
            panelAbsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAbsenLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelAbsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nama)
                    .addComponent(label_absen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(panelAbsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Kehadiran)
                    .addComponent(label_waktu))
                .addGap(35, 35, 35))
        );
        panelAbsenLayout.setVerticalGroup(
            panelAbsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAbsenLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelAbsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama)
                    .addComponent(label_Kehadiran))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAbsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_waktu)
                    .addComponent(label_absen))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelAbsen, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel label_Kehadiran;
    private javax.swing.JLabel label_absen;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_waktu;
    private javax.swing.JPanel panelAbsen;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends PresensiModel> jlist, PresensiModel e, int i, boolean bln, boolean bln1) {
        this.label_waktu.setText(e.getWaktu_masuk());
        this.label_Kehadiran.setText(e.getStatus());
        this.label_nama.setText(e.getName());       
        this.label_absen.setText(e.getId_rfid());        
        return this;
    }

}
